spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfolio.cgdrwidry3wi.ap-northeast-2.rds.amazonaws.com:3306/androg
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
  - /mappers/*.xml
