spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bagume619@gmail.com
    password: ixekzqmgromewdld
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfolio.cgdrwidry3wi.ap-northeast-2.rds.amazonaws.com:3306/androg
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
        
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 88838579524-1umcpuule7ak21e0bmbrgosjh1nigis5.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://port-0-androg-portfolio-app-back-7xwyjq992llitnrgqd.sel4.cloudtype.app/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: 28071fcf9324548813728c0ce3d2ecda
            client-secret: VbTwPTDvR5rqaOyIhbB039ce0nZKGlr
            redirect-uri: https://port-0-androg-portfolio-app-back-7xwyjq992llitnrgqd.sel4.cloudtype.app/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: gU7ZHAmj3YrqxImuY4zh
            client-secret: u3tM1t069m
            redirect-uri:  https://port-0-androg-portfolio-app-back-7xwyjq992llitnrgqd.sel4.cloudtype.app/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
             

mybatis:
  mapper-locations:
  - /mappers/*.xml

jwt:
  secret: ezV2FMXHX7bzV8eEL9lHf0MLSCnB5M6gtjcHmokIxABqjplbHtRypoN8H2vMTxVO
  
file:
#  path: C:\aws_project\workspace\androg\androg\upload\
#  path: /home/ubuntu/upload
  path: /app/upload/